# ==========================================================
# Day 01 : What is Machine Learning
# Repository : Machine Learning Foundation
# Author : Saloni Tiwari
# ==========================================================

print("=" * 60)
print("          MACHINE LEARNING FOUNDATIONS - DAY 01")
print("=" * 60)

print("\nWhat is Machine Learning?")
print("-" * 30)

print("""
Machine Learning (ML) is a branch of Artificial Intelligence (AI)
that enables computers to learn patterns from data and make
predictions or decisions without being explicitly programmed.

Instead of writing rules manually, we provide data and allow
the machine to learn from experience.
""")

print("\nExample:")
print("-" * 30)

study_hours = [2, 4, 6, 8, 10]
marks = [40, 50, 65, 80, 95]

for hours, score in zip(study_hours, marks):
    print(f"Study Hours: {hours} --> Marks: {score}")

print("\nObservation:")
print("As study hours increase, marks generally increase.")

print("""
A Machine Learning model can learn this relationship
and predict marks for new students based on study hours.
""")

print("\nApplications of Machine Learning")
print("-" * 30)

applications = [
    "Email Spam Detection",
    "Movie Recommendations",
    "Face Recognition",
    "Medical Diagnosis",
    "Fraud Detection",
    "Weather Prediction",
    "Self-Driving Cars",
    "Language Translation"
]

for i, app in enumerate(applications, start=1):
    print(f"{i}. {app}")

print("\nWhy Machine Learning?")
print("-" * 30)

print("""
✓ Learns from data
✓ Improves with experience
✓ Handles large datasets
✓ Finds hidden patterns
✓ Automates decision making
""")

print("\nDifference Between Traditional Programming and ML")
print("-" * 30)

print("""
Traditional Programming:
Input + Rules  ---> Output

Machine Learning:
Input + Output ---> Model Learns Rules
""")

print("\nKey Terms")
print("-" * 30)

print("Data      : Information used for learning")
print("Feature   : Input variable")
print("Target    : Output variable")
print("Model     : Learned pattern")
print("Prediction: Output generated by model")

print("\nDay 01 Summary")
print("-" * 30)

print("""
1. Machine Learning is a subset of AI.
2. ML learns patterns from data.
3. ML is used for prediction and decision-making.
4. Data is the foundation of ML.
5. Real-world applications exist in almost every industry.
""")

print("\nDay 01 Completed Successfully!")
print("=" * 60)